language: cpp

compiler:  
  - gcc
  - clang

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script: cmake --build .

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblua5.1-dev
