language: cpp

compiler:  
  - gcc
  - clang

before_script:  
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake ${TRAVIS_BUILD_DIR}

script: cmake --build .

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblua5.1-dev
